//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HeplersTitlesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HeplersTitlesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.HeplersTitlesResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple addition operation. 
        ///For example: 1 + 2 = 3.
        /// </summary>
        internal static string Addition {
            get {
                return ResourceManager.GetString("Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erects x to the power of y.
        ///For example: 3 ^ 3 = 27.
        /// </summary>
        internal static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation of division.
        ///For example: 10 / 2 = 5.
        /// </summary>
        internal static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return true if first number equal to second number, otherwise return false.
        ///For example: 4 == 5 = false.
        /// </summary>
        internal static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp is exponent function. Exp(x) is short name of e^x, where e is Euler&apos;s number.
        ///For example: exp(1) = e ^ 1 =  2.7182.
        /// </summary>
        internal static string Exp {
            get {
                return ResourceManager.GetString("Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The floor() method rounds a number downwards to the nearest integer.
        ///For example: floor(12.345) = 12.
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greatest common divisor is the largest positive integer that divides the numbers without a remainder.
        ///For example: gcd(2, 4, 6) = 2.
        /// </summary>
        internal static string GCD {
            get {
                return ResourceManager.GetString("GCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return true if first number more or equal than second number, otherwise return false.
        ///For example: 4 &gt;= 4 = true.
        /// </summary>
        internal static string GreatOrEqual {
            get {
                return ResourceManager.GetString("GreatOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return true if first number more than second number, otherwise return false.
        ///For example: 12 &gt; 3 = true.
        /// </summary>
        internal static string GreatThan {
            get {
                return ResourceManager.GetString("GreatThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Least common multiple is the smallest positive integer that is divisible by all of some numbers.
        ///For example: lcm(2, 4, 6) = 12..
        /// </summary>
        internal static string LCM {
            get {
                return ResourceManager.GetString("LCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return true if first number less or equal than second number, otherwise return false.
        ///For example: 4 &lt;= 5 = true.
        /// </summary>
        internal static string LessOrEqual {
            get {
                return ResourceManager.GetString("LessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return true if first number less than second number, otherwise return false.
        ///For example: 12 &lt; 3 = false.
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log(number, base) function is logarithm of a number is the exponent to which another fixed value, the base, must be raised to produce that number. In default case base equal to e.
        ///For example: log(100, 10) = 2, because 10^2 = 100
        ///log(e^2) = 2.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple modulo operation.
        ///For example: 13 % 3 = 1.
        /// </summary>
        internal static string Modulo {
            get {
                return ResourceManager.GetString("Modulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation of multiplication.
        ///For example: 12 * 4 = 48.
        /// </summary>
        internal static string Multiplication {
            get {
                return ResourceManager.GetString("Multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return true if first number not equal to second number, otherwise return false.
        ///For example: 4 != 5 = true.
        /// </summary>
        internal static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the root of y degree of number.
        ///For example: 32 ^ (1/5) = 2.
        /// </summary>
        internal static string ReverseDegree {
            get {
                return ResourceManager.GetString("ReverseDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The round(number, occuracy) method rounds a number to the nearest integer with specified occuracy. In default way occuracy equal to 0.
        ///For example: round(2.34) = 2 
        ///round(2.34, 1) = 2.3.
        /// </summary>
        internal static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return square root of number.
        ///For example: sqrt(4) = 2.
        /// </summary>
        internal static string Sqrt {
            get {
                return ResourceManager.GetString("Sqrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return second degree of number.
        ///For example: square(3) = 9.
        /// </summary>
        internal static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple subtraction operation.
        ///For example: 21 - 3 = 18.
        /// </summary>
        internal static string Substraction {
            get {
                return ResourceManager.GetString("Substraction", resourceCulture);
            }
        }
    }
}
